// Nombres de países en diferentes idiomas
export const countryNames = {
	es: {
		'Afganistán': 'Afganistán',
		'Albania': 'Albania',
		'Alemania': 'Alemania',
		'Andorra': 'Andorra',
		'Angola': 'Angola',
		'Antigua y Barbuda': 'Antigua y Barbuda',
		'Arabia Saudí': 'Arabia Saudí',
		'Argelia': 'Argelia',
		'Argentina': 'Argentina',
		'Armenia': 'Armenia',
		'Australia': 'Australia',
		'Austria': 'Austria',
		'Azerbaiyán': 'Azerbaiyán',
		'Bahamas': 'Bahamas',
		'Bangladés': 'Bangladés',
		'Barbados': 'Barbados',
		'Baréin': 'Baréin',
		'Belice': 'Belice',
		'Benín': 'Benín',
		'Bielorrusia': 'Bielorrusia',
		'Birmania': 'Birmania',
		'Bolivia': 'Bolivia',
		'Bosnia y Herzegovina': 'Bosnia y Herzegovina',
		'Botsuana': 'Botsuana',
		'Brasil': 'Brasil',
		'Brunéi': 'Brunéi',
		'Bulgaria': 'Bulgaria',
		'Burkina Faso': 'Burkina Faso',
		'Burundi': 'Burundi',
		'Bután': 'Bután',
		'Bélgica': 'Bélgica',
		'Cabo Verde': 'Cabo Verde',
		'Camboya': 'Camboya',
		'Camerún': 'Camerún',
		'Canadá': 'Canadá',
		'Catar': 'Catar',
		'Chad': 'Chad',
		'Chile': 'Chile',
		'China': 'China',
		'Chipre': 'Chipre',
		'Ciudad del Vaticano': 'Ciudad del Vaticano',
		'Colombia': 'Colombia',
		'Comoras': 'Comoras',
		'Corea del Norte': 'Corea del Norte',
		'Corea del Sur': 'Corea del Sur',
		'Costa de Marfil': 'Costa de Marfil',
		'Costa Rica': 'Costa Rica',
		'Croacia': 'Croacia',
		'Cuba': 'Cuba',
		'Dinamarca': 'Dinamarca',
		'Dominica': 'Dominica',
		'Ecuador': 'Ecuador',
		'Egipto': 'Egipto',
		'El Salvador': 'El Salvador',
		'Emiratos Árabes Unidos': 'Emiratos Árabes Unidos',
		'Eritrea': 'Eritrea',
		'Eslovaquia': 'Eslovaquia',
		'Eslovenia': 'Eslovenia',
		'España': 'España',
		'Estados Unidos': 'Estados Unidos',
		'Estonia': 'Estonia',
		'Esuatini': 'Esuatini',
		'Etiopía': 'Etiopía',
		'Filipinas': 'Filipinas',
		'Finlandia': 'Finlandia',
		'Fiyi': 'Fiyi',
		'Francia': 'Francia',
		'Gabón': 'Gabón',
		'Gambia': 'Gambia',
		'Georgia': 'Georgia',
		'Ghana': 'Ghana',
		'Granada': 'Granada',
		'Grecia': 'Grecia',
		'Guatemala': 'Guatemala',
		'Guinea Ecuatorial': 'Guinea Ecuatorial',
		'Guinea-Bissau': 'Guinea-Bissau',
		'Guinea': 'Guinea',
		'Guyana': 'Guyana',
		'Haití': 'Haití',
		'Honduras': 'Honduras',
		'Hungría': 'Hungría',
		'India': 'India',
		'Indonesia': 'Indonesia',
		'Irak': 'Irak',
		'Irlanda': 'Irlanda',
		'Irán': 'Irán',
		'Islandia': 'Islandia',
		'Islas Marshall': 'Islas Marshall',
		'Islas Salomón': 'Islas Salomón',
		'Israel': 'Israel',
		'Italia': 'Italia',
		'Jamaica': 'Jamaica',
		'Japón': 'Japón',
		'Jordania': 'Jordania',
		'Kazajistán': 'Kazajistán',
		'Kenia': 'Kenia',
		'Kirguistán': 'Kirguistán',
		'Kiribati': 'Kiribati',
		'Kuwait': 'Kuwait',
		'Laos': 'Laos',
		'Lesoto': 'Lesoto',
		'Letonia': 'Letonia',
		'Liberia': 'Liberia',
		'Libia': 'Libia',
		'Liechtenstein': 'Liechtenstein',
		'Lituania': 'Lituania',
		'Luxemburgo': 'Luxemburgo',
		'Líbano': 'Líbano',
		'Macedonia del Norte': 'Macedonia del Norte',
		'Madagascar': 'Madagascar',
		'Malasia': 'Malasia',
		'Malaui': 'Malaui',
		'Maldivas': 'Maldivas',
		'Malta': 'Malta',
		'Malí': 'Malí',
		'Marruecos': 'Marruecos',
		'Mauricio': 'Mauricio',
		'Mauritania': 'Mauritania',
		'Micronesia': 'Micronesia',
		'Moldavia': 'Moldavia',
		'Mongolia': 'Mongolia',
		'Montenegro': 'Montenegro',
		'Mozambique': 'Mozambique',
		'México': 'México',
		'Mónaco': 'Mónaco',
		'Namibia': 'Namibia',
		'Nauru': 'Nauru',
		'Nepal': 'Nepal',
		'Nicaragua': 'Nicaragua',
		'Nigeria': 'Nigeria',
		'Noruega': 'Noruega',
		'Nueva Zelanda': 'Nueva Zelanda',
		'Níger': 'Níger',
		'Omán': 'Omán',
		'Pakistán': 'Pakistán',
		'Palaos': 'Palaos',
		'Panamá': 'Panamá',
		'Papúa Nueva Guinea': 'Papúa Nueva Guinea',
		'Paraguay': 'Paraguay',
		'Países Bajos': 'Países Bajos',
		'Perú': 'Perú',
		'Polonia': 'Polonia',
		'Portugal': 'Portugal',
		'Reino Unido': 'Reino Unido',
		'República Centroafricana': 'República Centroafricana',
		'República Checa': 'República Checa',
		'República del Congo': 'República del Congo',
		'República Democrática del Congo': 'República Democrática del Congo',
		'República Dominicana': 'República Dominicana',
		'Ruanda': 'Ruanda',
		'Rumania': 'Rumania',
		'Rusia': 'Rusia',
		'Samoa': 'Samoa',
		'San Cristóbal y Nieves': 'San Cristóbal y Nieves',
		'San Marino': 'San Marino',
		'San Vicente y las Granadinas': 'San Vicente y las Granadinas',
		'Santa Lucía': 'Santa Lucía',
		'Santo Tomé y Príncipe': 'Santo Tomé y Príncipe',
		'Senegal': 'Senegal',
		'Serbia': 'Serbia',
		'Seychelles': 'Seychelles',
		'Sierra Leona': 'Sierra Leona',
		'Singapur': 'Singapur',
		'Siria': 'Siria',
		'Somalia': 'Somalia',
		'Sri Lanka': 'Sri Lanka',
		'Sudáfrica': 'Sudáfrica',
		'Sudán del Sur': 'Sudán del Sur',
		'Sudán': 'Sudán',
		'Suecia': 'Suecia',
		'Suiza': 'Suiza',
		'Surinam': 'Surinam',
		'Tailandia': 'Tailandia',
		'Tanzania': 'Tanzania',
		'Tayikistán': 'Tayikistán',
		'Timor Oriental': 'Timor Oriental',
		'Togo': 'Togo',
		'Tonga': 'Tonga',
		'Trinidad y Tobago': 'Trinidad y Tobago',
		'Turkmenistán': 'Turkmenistán',
		'Turquía': 'Turquía',
		'Tuvalu': 'Tuvalu',
		'Túnez': 'Túnez',
		'Ucrania': 'Ucrania',
		'Uganda': 'Uganda',
		'Uruguay': 'Uruguay',
		'Uzbekistán': 'Uzbekistán',
		'Vanuatu': 'Vanuatu',
		'Venezuela': 'Venezuela',
		'Vietnam': 'Vietnam',
		'Yemen': 'Yemen',
		'Yibuti': 'Yibuti',
		'Zambia': 'Zambia',
		'Zimbabue': 'Zimbabue'
	},
	en: {
		'Afganistán': 'Afghanistan',
		'Albania': 'Albania',
		'Alemania': 'Germany',
		'Andorra': 'Andorra',
		'Angola': 'Angola',
		'Antigua y Barbuda': 'Antigua and Barbuda',
		'Arabia Saudí': 'Saudi Arabia',
		'Argelia': 'Algeria',
		'Argentina': 'Argentina',
		'Armenia': 'Armenia',
		'Australia': 'Australia',
		'Austria': 'Austria',
		'Azerbaiyán': 'Azerbaijan',
		'Bahamas': 'Bahamas',
		'Bangladés': 'Bangladesh',
		'Barbados': 'Barbados',
		'Baréin': 'Bahrain',
		'Belice': 'Belize',
		'Benín': 'Benin',
		'Bielorrusia': 'Belarus',
		'Birmania': 'Myanmar',
		'Bolivia': 'Bolivia',
		'Bosnia y Herzegovina': 'Bosnia and Herzegovina',
		'Botsuana': 'Botswana',
		'Brasil': 'Brazil',
		'Brunéi': 'Brunei',
		'Bulgaria': 'Bulgaria',
		'Burkina Faso': 'Burkina Faso',
		'Burundi': 'Burundi',
		'Bután': 'Bhutan',
		'Bélgica': 'Belgium',
		'Cabo Verde': 'Cape Verde',
		'Camboya': 'Cambodia',
		'Camerún': 'Cameroon',
		'Canadá': 'Canada',
		'Catar': 'Qatar',
		'Chad': 'Chad',
		'Chile': 'Chile',
		'China': 'China',
		'Chipre': 'Cyprus',
		'Ciudad del Vaticano': 'Vatican City',
		'Colombia': 'Colombia',
		'Comoras': 'Comoros',
		'Corea del Norte': 'North Korea',
		'Corea del Sur': 'South Korea',
		'Costa de Marfil': 'Ivory Coast',
		'Costa Rica': 'Costa Rica',
		'Croacia': 'Croatia',
		'Cuba': 'Cuba',
		'Dinamarca': 'Denmark',
		'Dominica': 'Dominica',
		'Ecuador': 'Ecuador',
		'Egipto': 'Egypt',
		'El Salvador': 'El Salvador',
		'Emiratos Árabes Unidos': 'United Arab Emirates',
		'Eritrea': 'Eritrea',
		'Eslovaquia': 'Slovakia',
		'Eslovenia': 'Slovenia',
		'España': 'Spain',
		'Estados Unidos': 'United States',
		'Estonia': 'Estonia',
		'Esuatini': 'Eswatini',
		'Etiopía': 'Ethiopia',
		'Filipinas': 'Philippines',
		'Finlandia': 'Finland',
		'Fiyi': 'Fiji',
		'Francia': 'France',
		'Gabón': 'Gabon',
		'Gambia': 'Gambia',
		'Georgia': 'Georgia',
		'Ghana': 'Ghana',
		'Granada': 'Grenada',
		'Grecia': 'Greece',
		'Guatemala': 'Guatemala',
		'Guinea Ecuatorial': 'Equatorial Guinea',
		'Guinea-Bissau': 'Guinea-Bissau',
		'Guinea': 'Guinea',
		'Guyana': 'Guyana',
		'Haití': 'Haiti',
		'Honduras': 'Honduras',
		'Hungría': 'Hungary',
		'India': 'India',
		'Indonesia': 'Indonesia',
		'Irak': 'Iraq',
		'Irlanda': 'Ireland',
		'Irán': 'Iran',
		'Islandia': 'Iceland',
		'Islas Marshall': 'Marshall Islands',
		'Islas Salomón': 'Solomon Islands',
		'Israel': 'Israel',
		'Italia': 'Italy',
		'Jamaica': 'Jamaica',
		'Japón': 'Japan',
		'Jordania': 'Jordan',
		'Kazajistán': 'Kazakhstan',
		'Kenia': 'Kenya',
		'Kirguistán': 'Kyrgyzstan',
		'Kiribati': 'Kiribati',
		'Kuwait': 'Kuwait',
		'Laos': 'Laos',
		'Lesoto': 'Lesotho',
		'Letonia': 'Latvia',
		'Liberia': 'Liberia',
		'Libia': 'Libya',
		'Liechtenstein': 'Liechtenstein',
		'Lituania': 'Lithuania',
		'Luxemburgo': 'Luxembourg',
		'Líbano': 'Lebanon',
		'Macedonia del Norte': 'North Macedonia',
		'Madagascar': 'Madagascar',
		'Malasia': 'Malaysia',
		'Malaui': 'Malawi',
		'Maldivas': 'Maldives',
		'Malta': 'Malta',
		'Malí': 'Mali',
		'Marruecos': 'Morocco',
		'Mauricio': 'Mauritius',
		'Mauritania': 'Mauritania',
		'Micronesia': 'Micronesia',
		'Moldavia': 'Moldova',
		'Mongolia': 'Mongolia',
		'Montenegro': 'Montenegro',
		'Mozambique': 'Mozambique',
		'México': 'Mexico',
		'Mónaco': 'Monaco',
		'Namibia': 'Namibia',
		'Nauru': 'Nauru',
		'Nepal': 'Nepal',
		'Nicaragua': 'Nicaragua',
		'Nigeria': 'Nigeria',
		'Noruega': 'Norway',
		'Nueva Zelanda': 'New Zealand',
		'Níger': 'Niger',
		'Omán': 'Oman',
		'Pakistán': 'Pakistan',
		'Palaos': 'Palau',
		'Panamá': 'Panama',
		'Papúa Nueva Guinea': 'Papua New Guinea',
		'Paraguay': 'Paraguay',
		'Países Bajos': 'Netherlands',
		'Perú': 'Peru',
		'Polonia': 'Poland',
		'Portugal': 'Portugal',
		'Reino Unido': 'United Kingdom',
		'República Centroafricana': 'Central African Republic',
		'República Checa': 'Czech Republic',
		'República del Congo': 'Republic of the Congo',
		'República Democrática del Congo': 'Democratic Republic of the Congo',
		'República Dominicana': 'Dominican Republic',
		'Ruanda': 'Rwanda',
		'Rumania': 'Romania',
		'Rusia': 'Russia',
		'Samoa': 'Samoa',
		'San Cristóbal y Nieves': 'Saint Kitts and Nevis',
		'San Marino': 'San Marino',
		'San Vicente y las Granadinas': 'Saint Vincent and the Grenadines',
		'Santa Lucía': 'Saint Lucia',
		'Santo Tomé y Príncipe': 'São Tomé and Príncipe',
		'Senegal': 'Senegal',
		'Serbia': 'Serbia',
		'Seychelles': 'Seychelles',
		'Sierra Leona': 'Sierra Leone',
		'Singapur': 'Singapore',
		'Siria': 'Syria',
		'Somalia': 'Somalia',
		'Sri Lanka': 'Sri Lanka',
		'Sudáfrica': 'South Africa',
		'Sudán del Sur': 'South Sudan',
		'Sudán': 'Sudan',
		'Suecia': 'Sweden',
		'Suiza': 'Switzerland',
		'Surinam': 'Suriname',
		'Tailandia': 'Thailand',
		'Tanzania': 'Tanzania',
		'Tayikistán': 'Tajikistan',
		'Timor Oriental': 'East Timor',
		'Togo': 'Togo',
		'Tonga': 'Tonga',
		'Trinidad y Tobago': 'Trinidad and Tobago',
		'Turkmenistán': 'Turkmenistan',
		'Turquía': 'Turkey',
		'Tuvalu': 'Tuvalu',
		'Túnez': 'Tunisia',
		'Ucrania': 'Ukraine',
		'Uganda': 'Uganda',
		'Uruguay': 'Uruguay',
		'Uzbekistán': 'Uzbekistan',
		'Vanuatu': 'Vanuatu',
		'Venezuela': 'Venezuela',
		'Vietnam': 'Vietnam',
		'Yemen': 'Yemen',
		'Yibuti': 'Djibouti',
		'Zambia': 'Zambia',
		'Zimbabue': 'Zimbabwe'
	},
	fr: {
		'Afganistán': 'Afghanistan',
		'Albania': 'Albanie',
		'Alemania': 'Allemagne',
		'Andorra': 'Andorre',
		'Angola': 'Angola',
		'Antigua y Barbuda': 'Antigua-et-Barbuda',
		'Arabia Saudí': 'Arabie saoudite',
		'Argelia': 'Algérie',
		'Argentina': 'Argentine',
		'Armenia': 'Arménie',
		'Australia': 'Australie',
		'Austria': 'Autriche',
		'Azerbaiyán': 'Azerbaïdjan',
		'Bahamas': 'Bahamas',
		'Bangladés': 'Bangladesh',
		'Barbados': 'Barbade',
		'Baréin': 'Bahreïn',
		'Belice': 'Belize',
		'Benín': 'Bénin',
		'Bielorrusia': 'Biélorussie',
		'Birmania': 'Myanmar',
		'Bolivia': 'Bolivie',
		'Bosnia y Herzegovina': 'Bosnie-Herzégovine',
		'Botsuana': 'Botswana',
		'Brasil': 'Brésil',
		'Brunéi': 'Brunei',
		'Bulgaria': 'Bulgarie',
		'Burkina Faso': 'Burkina Faso',
		'Burundi': 'Burundi',
		'Bután': 'Bhoutan',
		'Bélgica': 'Belgique',
		'Cabo Verde': 'Cap-Vert',
		'Camboya': 'Cambodge',
		'Camerún': 'Cameroun',
		'Canadá': 'Canada',
		'Catar': 'Qatar',
		'Chad': 'Tchad',
		'Chile': 'Chili',
		'China': 'Chine',
		'Chipre': 'Chypre',
		'Ciudad del Vaticano': 'Vatican',
		'Colombia': 'Colombie',
		'Comoras': 'Comores',
		'Corea del Norte': 'Corée du Nord',
		'Corea del Sur': 'Corée du Sud',
		'Costa de Marfil': 'Côte d\'Ivoire',
		'Costa Rica': 'Costa Rica',
		'Croacia': 'Croatie',
		'Cuba': 'Cuba',
		'Dinamarca': 'Danemark',
		'Dominica': 'Dominique',
		'Ecuador': 'Équateur',
		'Egipto': 'Égypte',
		'El Salvador': 'Salvador',
		'Emiratos Árabes Unidos': 'Émirats arabes unis',
		'Eritrea': 'Érythrée',
		'Eslovaquia': 'Slovaquie',
		'Eslovenia': 'Slovénie',
		'España': 'Espagne',
		'Estados Unidos': 'États-Unis',
		'Estonia': 'Estonie',
		'Esuatini': 'Eswatini',
		'Etiopía': 'Éthiopie',
		'Filipinas': 'Philippines',
		'Finlandia': 'Finlande',
		'Fiyi': 'Fidji',
		'Francia': 'France',
		'Gabón': 'Gabon',
		'Gambia': 'Gambie',
		'Georgia': 'Géorgie',
		'Ghana': 'Ghana',
		'Granada': 'Grenade',
		'Grecia': 'Grèce',
		'Guatemala': 'Guatemala',
		'Guinea Ecuatorial': 'Guinée équatoriale',
		'Guinea-Bissau': 'Guinée-Bissau',
		'Guinea': 'Guinée',
		'Guyana': 'Guyana',
		'Haití': 'Haïti',
		'Honduras': 'Honduras',
		'Hungría': 'Hongrie',
		'India': 'Inde',
		'Indonesia': 'Indonésie',
		'Irak': 'Irak',
		'Irlanda': 'Irlande',
		'Irán': 'Iran',
		'Islandia': 'Islande',
		'Islas Marshall': 'Îles Marshall',
		'Islas Salomón': 'Îles Salomon',
		'Israel': 'Israël',
		'Italia': 'Italie',
		'Jamaica': 'Jamaïque',
		'Japón': 'Japon',
		'Jordania': 'Jordanie',
		'Kazajistán': 'Kazakhstan',
		'Kenia': 'Kenya',
		'Kirguistán': 'Kirghizistan',
		'Kiribati': 'Kiribati',
		'Kuwait': 'Koweït',
		'Laos': 'Laos',
		'Lesoto': 'Lesotho',
		'Letonia': 'Lettonie',
		'Liberia': 'Liberia',
		'Libia': 'Libye',
		'Liechtenstein': 'Liechtenstein',
		'Lituania': 'Lituanie',
		'Luxemburgo': 'Luxembourg',
		'Líbano': 'Liban',
		'Macedonia del Norte': 'Macédoine du Nord',
		'Madagascar': 'Madagascar',
		'Malasia': 'Malaisie',
		'Malaui': 'Malawi',
		'Maldivas': 'Maldives',
		'Malta': 'Malte',
		'Malí': 'Mali',
		'Marruecos': 'Maroc',
		'Mauricio': 'Maurice',
		'Mauritania': 'Mauritanie',
		'Micronesia': 'Micronésie',
		'Moldavia': 'Moldavie',
		'Mongolia': 'Mongolie',
		'Montenegro': 'Monténégro',
		'Mozambique': 'Mozambique',
		'México': 'Mexique',
		'Mónaco': 'Monaco',
		'Namibia': 'Namibie',
		'Nauru': 'Nauru',
		'Nepal': 'Népal',
		'Nicaragua': 'Nicaragua',
		'Nigeria': 'Nigeria',
		'Noruega': 'Norvège',
		'Nueva Zelanda': 'Nouvelle-Zélande',
		'Níger': 'Niger',
		'Omán': 'Oman',
		'Pakistán': 'Pakistan',
		'Palaos': 'Palaos',
		'Panamá': 'Panama',
		'Papúa Nueva Guinea': 'Papouasie-Nouvelle-Guinée',
		'Paraguay': 'Paraguay',
		'Países Bajos': 'Pays-Bas',
		'Perú': 'Pérou',
		'Polonia': 'Pologne',
		'Portugal': 'Portugal',
		'Reino Unido': 'Royaume-Uni',
		'República Centroafricana': 'République centrafricaine',
		'República Checa': 'République tchèque',
		'República del Congo': 'République du Congo',
		'República Democrática del Congo': 'République démocratique du Congo',
		'República Dominicana': 'République dominicaine',
		'Ruanda': 'Rwanda',
		'Rumania': 'Roumanie',
		'Rusia': 'Russie',
		'Samoa': 'Samoa',
		'San Cristóbal y Nieves': 'Saint-Christophe-et-Niévès',
		'San Marino': 'Saint-Marin',
		'San Vicente y las Granadinas': 'Saint-Vincent-et-les-Grenadines',
		'Santa Lucía': 'Sainte-Lucie',
		'Santo Tomé y Príncipe': 'Sao Tomé-et-Principe',
		'Senegal': 'Sénégal',
		'Serbia': 'Serbie',
		'Seychelles': 'Seychelles',
		'Sierra Leona': 'Sierra Leone',
		'Singapur': 'Singapour',
		'Siria': 'Syrie',
		'Somalia': 'Somalie',
		'Sri Lanka': 'Sri Lanka',
		'Sudáfrica': 'Afrique du Sud',
		'Sudán del Sur': 'Soudan du Sud',
		'Sudán': 'Soudan',
		'Suecia': 'Suède',
		'Suiza': 'Suisse',
		'Surinam': 'Suriname',
		'Tailandia': 'Thaïlande',
		'Tanzania': 'Tanzanie',
		'Tayikistán': 'Tadjikistan',
		'Timor Oriental': 'Timor oriental',
		'Togo': 'Togo',
		'Tonga': 'Tonga',
		'Trinidad y Tobago': 'Trinité-et-Tobago',
		'Turkmenistán': 'Turkménistan',
		'Turquía': 'Turquie',
		'Tuvalu': 'Tuvalu',
		'Túnez': 'Tunisie',
		'Ucrania': 'Ukraine',
		'Uganda': 'Ouganda',
		'Uruguay': 'Uruguay',
		'Uzbekistán': 'Ouzbékistan',
		'Vanuatu': 'Vanuatu',
		'Venezuela': 'Venezuela',
		'Vietnam': 'Viêt Nam',
		'Yemen': 'Yémen',
		'Yibuti': 'Djibouti',
		'Zambia': 'Zambie',
		'Zimbabue': 'Zimbabwe'
	}
};

// Función para obtener el nombre del país en el idioma actual
export function getCountryName(originalName, language = 'es') {
	return countryNames[language]?.[originalName] || originalName;
}